-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- PROGRAM		"Quartus II 64-Bit"
-- VERSION		"Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition"
-- CREATED		"Sat Nov 22 18:21:13 2025"

LIBRARY ieee;
USE ieee.std_logic_1164.all; 

LIBRARY work;

ENTITY controller IS 
	PORT
	(
		i :  IN  STD_LOGIC;
		CLK :  IN  STD_LOGIC;
		start :  IN  STD_LOGIC;
		S :  OUT  STD_LOGIC;
		E :  OUT  STD_LOGIC;
		D :  OUT  STD_LOGIC;
		Load :  OUT  STD_LOGIC;
		OE :  OUT  STD_LOGIC;
		Select_mux :  OUT  STD_LOGIC
	);
END controller;

ARCHITECTURE bdf_type OF controller IS 

SIGNAL	SYNTHESIZED_WIRE_0 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_1 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_22 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_23 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_2 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_24 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_4 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_25 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_26 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_7 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_9 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_27 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_28 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_19 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_20 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_21 :  STD_LOGIC;


BEGIN 
S <= SYNTHESIZED_WIRE_21;
E <= SYNTHESIZED_WIRE_20;
D <= SYNTHESIZED_WIRE_20;
Select_mux <= SYNTHESIZED_WIRE_21;



PROCESS(CLK)
BEGIN
IF (RISING_EDGE(CLK)) THEN
	SYNTHESIZED_WIRE_22 <= SYNTHESIZED_WIRE_0;
END IF;
END PROCESS;


PROCESS(CLK)
BEGIN
IF (RISING_EDGE(CLK)) THEN
	SYNTHESIZED_WIRE_23 <= SYNTHESIZED_WIRE_1;
END IF;
END PROCESS;


SYNTHESIZED_WIRE_19 <= SYNTHESIZED_WIRE_22 AND SYNTHESIZED_WIRE_23 AND i;


SYNTHESIZED_WIRE_0 <= SYNTHESIZED_WIRE_2 OR SYNTHESIZED_WIRE_24 OR SYNTHESIZED_WIRE_4;


SYNTHESIZED_WIRE_2 <= SYNTHESIZED_WIRE_25 AND SYNTHESIZED_WIRE_23;


SYNTHESIZED_WIRE_25 <= NOT(SYNTHESIZED_WIRE_22);



SYNTHESIZED_WIRE_26 <= NOT(SYNTHESIZED_WIRE_23);



SYNTHESIZED_WIRE_24 <= SYNTHESIZED_WIRE_22 AND SYNTHESIZED_WIRE_26;


SYNTHESIZED_WIRE_4 <= SYNTHESIZED_WIRE_7 AND SYNTHESIZED_WIRE_23 AND SYNTHESIZED_WIRE_22;


SYNTHESIZED_WIRE_1 <= SYNTHESIZED_WIRE_24 OR SYNTHESIZED_WIRE_9;


SYNTHESIZED_WIRE_9 <= start AND SYNTHESIZED_WIRE_27 AND SYNTHESIZED_WIRE_26;


SYNTHESIZED_WIRE_27 <= NOT(SYNTHESIZED_WIRE_28);



SYNTHESIZED_WIRE_21 <= SYNTHESIZED_WIRE_27 AND SYNTHESIZED_WIRE_25 AND SYNTHESIZED_WIRE_23;


SYNTHESIZED_WIRE_20 <= SYNTHESIZED_WIRE_27 AND SYNTHESIZED_WIRE_22 AND SYNTHESIZED_WIRE_23;


Load <= SYNTHESIZED_WIRE_27 AND SYNTHESIZED_WIRE_22 AND SYNTHESIZED_WIRE_26;


OE <= SYNTHESIZED_WIRE_28 AND SYNTHESIZED_WIRE_25 AND SYNTHESIZED_WIRE_26;


SYNTHESIZED_WIRE_7 <= NOT(i);



PROCESS(CLK)
BEGIN
IF (RISING_EDGE(CLK)) THEN
	SYNTHESIZED_WIRE_28 <= SYNTHESIZED_WIRE_19;
END IF;
END PROCESS;


END bdf_type;