-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- PROGRAM		"Quartus II 64-Bit"
-- VERSION		"Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition"
-- CREATED		"Mon Oct 27 10:07:44 2025"

LIBRARY ieee;
USE ieee.std_logic_1164.all; 

LIBRARY work;

ENTITY LAB3_1 IS 
	PORT
	(
		A :  IN  STD_LOGIC_VECTOR(3 DOWNTO 0);
		B :  IN  STD_LOGIC_VECTOR(3 DOWNTO 0);
		OUTPUT :  OUT  STD_LOGIC_VECTOR(7 DOWNTO 0)
	);
END LAB3_1;

ARCHITECTURE bdf_type OF LAB3_1 IS 

COMPONENT fulladder
	PORT(A : IN STD_LOGIC;
		 B : IN STD_LOGIC;
		 Cin : IN STD_LOGIC;
		 S : OUT STD_LOGIC;
		 Cout : OUT STD_LOGIC
	);
END COMPONENT;

SIGNAL	OUTPUT_ALTERA_SYNTHESIZED :  STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_0 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_1 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_2 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_3 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_4 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_5 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_6 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_7 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_8 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_9 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_10 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_11 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_12 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_13 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_14 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_15 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_16 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_17 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_18 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_19 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_20 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_21 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_22 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_23 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_24 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_25 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_26 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_27 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_28 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_29 :  STD_LOGIC;


BEGIN 
SYNTHESIZED_WIRE_2 <= '0';
SYNTHESIZED_WIRE_29 <= '0';



b2v_inst : fulladder
PORT MAP(A => SYNTHESIZED_WIRE_0,
		 B => SYNTHESIZED_WIRE_1,
		 Cin => SYNTHESIZED_WIRE_2,
		 S => OUTPUT_ALTERA_SYNTHESIZED(1),
		 Cout => SYNTHESIZED_WIRE_5);


b2v_inst11 : fulladder
PORT MAP(A => SYNTHESIZED_WIRE_3,
		 B => SYNTHESIZED_WIRE_4,
		 Cin => SYNTHESIZED_WIRE_5,
		 S => SYNTHESIZED_WIRE_6,
		 Cout => SYNTHESIZED_WIRE_8);


b2v_inst12 : fulladder
PORT MAP(A => SYNTHESIZED_WIRE_6,
		 B => SYNTHESIZED_WIRE_7,
		 Cin => SYNTHESIZED_WIRE_8,
		 S => OUTPUT_ALTERA_SYNTHESIZED(2),
		 Cout => SYNTHESIZED_WIRE_11);


SYNTHESIZED_WIRE_10 <= A(2) AND B(1);


SYNTHESIZED_WIRE_18 <= A(3) AND B(1);


SYNTHESIZED_WIRE_7 <= A(0) AND B(2);


SYNTHESIZED_WIRE_13 <= A(1) AND B(2);


SYNTHESIZED_WIRE_19 <= A(2) AND B(2);


SYNTHESIZED_WIRE_24 <= A(3) AND B(2);


SYNTHESIZED_WIRE_12 <= A(0) AND B(3);


SYNTHESIZED_WIRE_22 <= A(1) AND B(3);


SYNTHESIZED_WIRE_25 <= A(2) AND B(3);


SYNTHESIZED_WIRE_27 <= A(3) AND B(3);


b2v_inst23 : fulladder
PORT MAP(A => SYNTHESIZED_WIRE_9,
		 B => SYNTHESIZED_WIRE_10,
		 Cin => SYNTHESIZED_WIRE_11,
		 S => SYNTHESIZED_WIRE_15,
		 Cout => SYNTHESIZED_WIRE_14);


b2v_inst24 : fulladder
PORT MAP(A => SYNTHESIZED_WIRE_12,
		 B => SYNTHESIZED_WIRE_13,
		 Cin => SYNTHESIZED_WIRE_14,
		 S => SYNTHESIZED_WIRE_16,
		 Cout => SYNTHESIZED_WIRE_17);


b2v_inst25 : fulladder
PORT MAP(A => SYNTHESIZED_WIRE_15,
		 B => SYNTHESIZED_WIRE_16,
		 Cin => SYNTHESIZED_WIRE_17,
		 S => OUTPUT_ALTERA_SYNTHESIZED(3),
		 Cout => SYNTHESIZED_WIRE_20);


b2v_inst26 : fulladder
PORT MAP(A => SYNTHESIZED_WIRE_18,
		 B => SYNTHESIZED_WIRE_19,
		 Cin => SYNTHESIZED_WIRE_20,
		 S => SYNTHESIZED_WIRE_21,
		 Cout => SYNTHESIZED_WIRE_23);


b2v_inst27 : fulladder
PORT MAP(A => SYNTHESIZED_WIRE_21,
		 B => SYNTHESIZED_WIRE_22,
		 Cin => SYNTHESIZED_WIRE_23,
		 S => OUTPUT_ALTERA_SYNTHESIZED(4),
		 Cout => SYNTHESIZED_WIRE_26);


b2v_inst28 : fulladder
PORT MAP(A => SYNTHESIZED_WIRE_24,
		 B => SYNTHESIZED_WIRE_25,
		 Cin => SYNTHESIZED_WIRE_26,
		 S => OUTPUT_ALTERA_SYNTHESIZED(5),
		 Cout => SYNTHESIZED_WIRE_28);


b2v_inst29 : fulladder
PORT MAP(A => SYNTHESIZED_WIRE_27,
		 B => SYNTHESIZED_WIRE_28,
		 Cin => SYNTHESIZED_WIRE_29,
		 S => OUTPUT_ALTERA_SYNTHESIZED(6),
		 Cout => OUTPUT_ALTERA_SYNTHESIZED(7));




OUTPUT_ALTERA_SYNTHESIZED(0) <= A(0) AND B(0);


SYNTHESIZED_WIRE_0 <= A(1) AND B(0);


SYNTHESIZED_WIRE_3 <= A(2) AND B(0);


SYNTHESIZED_WIRE_9 <= A(3) AND B(0);


SYNTHESIZED_WIRE_1 <= A(0) AND B(1);


SYNTHESIZED_WIRE_4 <= A(1) AND B(1);

OUTPUT <= OUTPUT_ALTERA_SYNTHESIZED;

END bdf_type;